
[server "http"]
    port = 7852

[data]
    groups = markets
    sources = main

[datagroup "markets"]

    alias = markets
    datasource = main
    enabled = 1
    table-name-prefix = markets_
    uri = uri:datagroup:default#markets

[datasource "main"]
    database = markets
    driver = mysql
    enabled = 1
    host = localhost
    name = main
    password = markets
    port = 0
    prefix = markets_
    uri = uri:datasource:main#markets
    username = markets

